version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /home/volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

  desafio-toro-backend:
    image: desafio-toro-backend
    ports: 
      - "5000:5000"
    restart: always
    networks:
      - mongo-compose-network
    depends_on:
      - mongo

  desafio-toro-frontend:
    image: desafio-toro-frontend
    ports: 
      - "4200:80"
    restart: always
    networks:
      - mongo-compose-network    
    depends_on:
      - desafio-toro-backend

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo_express_user
      ME_CONFIG_BASICAUTH_PASSWORD: mongo_express_password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_password
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge