name: App Docker-Compose CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-images:

    runs-on: self-hosted

    steps:
    - name: Executar comando whoami
      run: |
          echo "O usuário atual é: $(whoami)"
    
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |         
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin        
    - name: docker build backend
      run: | 
        cd backend
        docker build . -t thiagoinhan/desafio-toro-backend-arm64:1.0.0 --platform linux/arm64
    - name: docker push backend
      run: |
        docker push thiagoinhan/desafio-toro-backend-arm64:1.0.0
    - name: docker build frontend
      run: |
        cd frontend/Toro.Accounting.WebUI
        docker build . -t thiagoinhan/desafio-toro-frontend-arm64:1.0.0 --platform linux/arm64
    - name: docker push frontend
      run: |
        docker push thiagoinhan/desafio-toro-frontend-arm64:1.0.0

  run-docker-compose:

    runs-on: self-hosted

    steps:    
    - name: Pull images
      run: docker-compose -f docker-compose-arm64.yml pull
    - name: Run compose
      run: docker-compose -f docker-compose-arm64.yml up -d
