name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:    
    - name: Pull images
      run: docker-compose pull
    - name: Run compose
      run: docker-compose up -d
